const Mongoose = require("mongoose");
const Schema = Mongoose.Schema;
const studentSchema = new Schema({
    Name: {type: String, },
    LastName: {type: String, },
    FatherName: {type: String, },
    GrandFather: {type: String, },
    Skin: {type: String, },
    Page: {type: Number, },
    Register: {type: Number, },
    SakokNumber: {type: Number, },
    MainVillage: {type: String, },
    MainRegion: {type: String, },
    MainProvince: {type: String, },
    CurrentVillage: {type: String, },
    CurrentRegion: {type: String, },
    CurrentProvince: {type: String, },
    ClassGraduted: {type: Number, },
    Year: {type: String, },
    School: {type: String, },
    Province: {type: String, },
    KonkorID: {type: String, },
    KonkorScore: {type: Number, },
    PhoneNumber: {type: Number, },
    RelationContactNumber: {type: Number, },
    BaseNumber: {type: Number, },
    Nationality: {type: String, },
    RegisterWrittenNumber: {type: Number, },
    WrittenNumber: {type: Number,},
    EnrollDate:String,
    FatherJoblocation:String,
    FatherJob:String,
    BirthYear:String,
    Department:String,
    GraduationYear:String,
    semster:String,
    Lunch:String,
    className:String,
    nameOfClass:String,
    image:{type:String},
    s_deleted:Number
});
module.exports = Mongoose.model("StudentRegistration", studentSchema);